apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
      rollingUpdate:
          maxSurge: 1
          maxUnavailabel: 1
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      - name: {{ .Values.service.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullpolicy }}
        ports:
        - containerPort: 80
        volumeMounts:
          - name: {{ .Values.volume.name }}
            mountPath: /etc/nginx/conf.d/
      volumes:
        - name: {{ .Values.volume.name }}
          configMap:
              name: {{ .Values.service.name }}
